### ISSUE TITLE
[New] Self-Identity vs. Professional Presentation for Performer's Gender

### ISSUE THREAD

**Issue by Fish-track** [stashapp/StashDB-Docs#31]
This discussion started on the Stash Discord in #stashdb-general (originally by Norse and later me; Fishtrack), and i am now posting it here to attempt to get to a resolution.

The issue is whether performers gender on StashDB should be listed as either what the performer identifies as and prefers being called. Or whether they should be listed as the general identity they go by in their work.

This problem currently leads to performers gender being switched around every few weeks, which in turn creates confusion. A good current example of this is Lulu Chu [](https://stashdb.org/performers/bd35b62e-fac2-4a27-beba-ef4933e780fd), who's gender was first set to female then changed to non-binary (what she identifies as) and then shortly after changed back to female.

I understand that what people identify as may be a sensitive subject for some people but it is important we reach a agreement, so we can atleast reduce the amount of needles gender changes on StashDB.

To be completely clear this issue relates to ALL performers and isn't exclusive to a single case like Lulu Chu.

Feel free to expand on the issue or say what you think.

**Comment by Valmox** [comment]
Whilst I don't wish to comment on the topic at this point, the example Fish-track references with Lulu Chan and the impact it has on the DB can be seen in the edits here: [Lulu Chan](https://stashdb.org/performers/bd35b62e-fac2-4a27-beba-ef4933e780fd#edits)

**Comment by AdultSun** [comment]
I feel like either side we land on here, the other side won't be happy about it. The only compromise between the two I can think of would require a new feature built into Stash-Box: specifically, a new performer field listing preferred pronouns. The existing field for gender can be used for "professional presentation" and a new pronoun field can be used to clarify when and how that may differ from how they personally identify. But without that, I can only see the two mutually exclusive approaches as listed in the original post here.

Most of our guideline proposals are presented as either Approve or Reject. I expect this one would have to be between Option A, Option B, or None of the Above.

**Comment by myalow** [comment]
I think just doing a sex and gender field would be the easiest solution. Cis woman? sex = f gender = f. Trans woman? sex = m gender = f.
or you could just add a radio toggle: penis / vagina. :P

**Comment by AdultSun** [comment]
I mentioned this issue in the PR for Stash linked above. I propose a list of options for a new "Penis Type" performer field in [my comment linked here](https://github.com/stashapp/stash/pull/3627#issuecomment-1554301829) (in short: `Cut`/`Uncut`/`Natural`/`None`/`Removed`/`Augmented`/`Artificial`/`Intersex`) that could also be included in Stash-Box. I also mention some similar options for "Breast Type" (`Natural`/`Augmented`/`Reduced`/`Removed`/`None`).

With an expanded set of options like those, it may allow us to divorce the "Gender" field from also trying to describe what can be called _body configurations_ (not my term but feels appropriate here). For example, someone like Lulu Chu could still have typical cis female characteristics described in these body configuration fields (`Natural` for breasts and `None` for penis) but still have `Non-Binary` selected for gender. Users could then filter based on whichever combination of personal identity (under "Gender") and body configuration (under "Penis Type" and "Breast Type") is more important to them at that time. The most common combinations would still be easily found under simply `Female`, `Male`, `Trans Female`, etc. as users would expect, so nothing would functionally change there. But for anyone interested in drilling down into more detail, we would have more options to differentiate between less common situations like AFAB vs. AMAB non-binary, post-op vs. pre-op trans woman, etc.

Tracking these details already seems useful enough outside of this discussion to be worth adding to performer profiles, but hopefully this approach would also be less confusing than trying to parse and explain the difference between "personal gender identity" and "professional gender presentation" for edge cases like Lulu Chu. It may take awhile to get those options built into both Stash and Stash-Box, so in the meantime we could establish the "Gender" field as "personal gender identity" in the guidelines in preparation for the addition of expanded body configuration options.

Another consideration I mention in the PR thread linked above is `Intersex` as an option under gender (which is where it currently is in Stash and Stash-Box) vs. `Intersex` as an option under "Penis Type". It's my understanding that someone's intersex status (formerly known as hermaphrodite for those unfamiliar) doesn't have any bearing on their gender identity. So if we're splitting up gender identity and body configurations in performer profiles, then it seems to me that `Intersex` would only be a relevant option under "Penis Type". I'm also not aware of any post-op intersex performers (who now only have one set of genitals), but of course anything's possible. In that situation, I feel like their intersex status wouldn't be as relevant to StashDB anymore and could be handled with the other options already mentioned here, even if that results in data indistinguishable from a cis performer like `Female` for gender + `Natural` for breasts + `None` for penis. But that topic is probably better suited for a later discussion and guideline though, particularly if the hypothetical becomes reality.

Anyways, I've gone long and it's now way past my bedtime as I write this. Hopefully this makes sense in the morning.
