### ISSUE TITLE
[New] Static vs. Animated Images

### ISSUE THREAD

**Issue by AdultSun** [stashapp/StashDB-Docs#50]
Occasionally, studios will use an animated image (GIF or WEBP) as a scene cover. I believe BangBros will do this for some scenes. Though Infinite has previously stated that he isn't concerned with the increase in size for animated images, the general consensus has been to replace them with static equivalents instead. This is mostly for a desire for consistency across StashDB, though size and bandwidth could be a concern for any users pulling a lot of these images into Stash.

Users have also discovered that animated images are already supported in Stash for both performers and tags. StashDB does not host any tag images at this time, but I believe the same desire to avoid animated images for scene covers should apply to performers as well. We will need to add new guideline sections clarifying this stance for both scenes and performers.

Also worth noting that I don't believe we would need to restrict animated images for any of these objects if we were able to save multiple images and label them accordingly. I laid out some options in [this old RFC](https://github.com/stashapp/stash-box/issues/237) for performer image categories. We could include "animated" as an option in addition to the others mentioned there like crop, pose, state of dress, etc. I imagine a similar system for scene covers could work as well, supporting multiple images labelled appropriately like "official", "custom", "3rd party", "scene cover", "thumbnail", "screenshot", and of course "animated." I can't find an existing issue for alternate scene covers in the Stash-Box repo yet, but I can add one.

**Comment by AdultSun** [comment]
Submitted a feature request to the Stash-Box repo for alternate scene covers: https://github.com/stashapp/stash-box/issues/648

**Comment by DogmaDragon** [comment]
I know animated images are popular in some circles, but generally for a database static images are preffered.

**Comment by AdultSun** [comment]
Agreed, I've got a PR going up soon for this.
